# Source lists for RelayDock targets.
#
# RELAYDOCK_CORE_SOURCES       Logic with no OBS and no Qt dependency. Unit tested.
# RELAYDOCK_PLUGIN_SOURCES     OBS and Qt code for the plugin module.
# RELAYDOCK_TEST_HOOK_SOURCES  Scenario runner, compiled only with RELAYDOCK_TEST_HOOKS=ON.

set(
  RELAYDOCK_CORE_SOURCES
  src/build_info.cpp
  src/build_info.h
  src/chat/chat_types.cpp
  src/chat/chat_types.h
  src/chat/chat_worker.cpp
  src/chat/chat_worker.h
  src/chat/twitch_chat.cpp
  src/chat/twitch_chat.h
  src/chat/twitch_protocol.cpp
  src/chat/twitch_protocol.h
  src/chat/youtube_chat.cpp
  src/chat/youtube_chat.h
  src/chat/youtube_protocol.cpp
  src/chat/youtube_protocol.h
  src/core/destination_state.cpp
  src/core/destination_state.h
  src/core/output_stop.h
  src/core/types.cpp
  src/core/types.h
  src/core/user_message.h
  src/core/vertical_layout.cpp
  src/core/vertical_layout.h
  src/diagnostics/preflight.cpp
  src/diagnostics/preflight.h
  src/diagnostics/report.cpp
  src/diagnostics/report.h
  src/encoders/encode_plan.cpp
  src/encoders/encode_plan.h
  src/encoders/encoder_caps.cpp
  src/encoders/encoder_caps.h
  src/encoders/encoder_settings.cpp
  src/encoders/encoder_settings.h
  src/encoders/video_math.cpp
  src/encoders/video_math.h
  src/legal/legal_documents.cpp
  src/legal/legal_documents.h
  src/network/bandwidth.cpp
  src/network/bandwidth.h
  src/network/http_client.cpp
  src/network/http_client.h
  src/network/reachability.cpp
  src/network/reachability.h
  src/network/stream_url.cpp
  src/network/stream_url.h
  src/network/websocket_client.cpp
  src/network/websocket_client.h
  src/network/winhttp_async.h
  src/performance/effective_settings.cpp
  src/performance/effective_settings.h
  src/performance/metrics_window.cpp
  src/performance/metrics_window.h
  src/performance/optimizer.cpp
  src/performance/optimizer.h
  src/performance/optimizer_text.cpp
  src/performance/optimizer_text.h
  src/performance/system_sampler.cpp
  src/performance/system_sampler.h
  src/providers/custom_rtmp/custom_rtmp_provider.cpp
  src/providers/custom_rtmp/custom_rtmp_provider.h
  src/providers/facebook/facebook_provider.cpp
  src/providers/facebook/facebook_provider.h
  src/providers/provider.h
  src/providers/provider_base.cpp
  src/providers/provider_base.h
  src/providers/provider_registry.cpp
  src/providers/provider_registry.h
  src/providers/tiktok/tiktok_provider.cpp
  src/providers/tiktok/tiktok_provider.h
  src/providers/twitch/twitch_provider.cpp
  src/providers/twitch/twitch_provider.h
  src/providers/youtube/youtube_provider.cpp
  src/providers/youtube/youtube_provider.h
  src/security/credential_store.cpp
  src/security/credential_store.h
  src/security/memory_credential_store.cpp
  src/security/memory_credential_store.h
  src/security/redactor.cpp
  src/security/redactor.h
  src/security/secret_string.cpp
  src/security/secret_string.h
  src/security/secret_vault.cpp
  src/security/secret_vault.h
  src/security/secure_zero.cpp
  src/security/secure_zero.h
  src/security/windows_credential_store.cpp
  src/security/windows_credential_store.h
  src/settings/app_config.cpp
  src/settings/app_config.h
  src/settings/config_json.cpp
  src/settings/config_json.h
  src/settings/config_store.cpp
  src/settings/config_store.h
  src/settings/migrations.cpp
  src/settings/migrations.h
  src/settings/theme.cpp
  src/settings/theme.h
  src/update/update_check.cpp
  src/update/update_check.h
  src/utils/clock.cpp
  src/utils/clock.h
  src/utils/i18n.cpp
  src/utils/i18n.h
  src/utils/log.cpp
  src/utils/log.h
  src/utils/paths.cpp
  src/utils/paths.h
  src/utils/sleep_inhibitor.cpp
  src/utils/sleep_inhibitor.h
  src/utils/strings.cpp
  src/utils/strings.h
  src/utils/system_info.cpp
  src/utils/system_info.h
  src/utils/uuid.cpp
  src/utils/uuid.h
)

set(
  RELAYDOCK_PLUGIN_SOURCES
  resources/relaydock.qrc
  src/app/app_context.cpp
  src/app/app_context.h
  src/app/background_tasks.cpp
  src/app/background_tasks.h
  src/app/diagnostics_service.cpp
  src/app/diagnostics_service.h
  src/app/performance_monitor.cpp
  src/app/performance_monitor.h
  src/encoders/encoder_catalog.cpp
  src/encoders/encoder_catalog.h
  src/encoders/encoder_pool.cpp
  src/encoders/encoder_pool.h
  src/outputs/output_manager.cpp
  src/outputs/output_manager.h
  src/outputs/program_mirror_source.cpp
  src/outputs/program_mirror_source.h
  src/outputs/vertical_canvas.cpp
  src/outputs/vertical_canvas.h
  src/outputs/video_guard.cpp
  src/outputs/video_guard.h
  src/plugin-main.cpp
  src/ui/destination_card.cpp
  src/ui/destination_card.h
  src/ui/destination_dialog.cpp
  src/ui/destination_dialog.h
  src/ui/dock_widget.cpp
  src/ui/dock_widget.h
  src/ui/exit_guard.cpp
  src/ui/exit_guard.h
  src/ui/key_clipboard.cpp
  src/ui/key_clipboard.h
  src/ui/legal_dialog.cpp
  src/ui/legal_dialog.h
  src/ui/preflight_dialog.cpp
  src/ui/preflight_dialog.h
  src/ui/settings_dialog.cpp
  src/ui/settings_dialog.h
  src/ui/settings_pages.cpp
  src/ui/ui_common.cpp
  src/ui/ui_common.h
  src/ui/update_dialog.cpp
  src/ui/update_dialog.h
  src/ui/vertical_editor.cpp
  src/ui/vertical_editor.h
)

set(
  RELAYDOCK_TEST_HOOK_SOURCES
  src/testing/scenario_runner.cpp
  src/testing/scenario_runner.h
  src/testing/scenario_ui.cpp
)
